# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - id: protoc-gen-connect-ktor
    dir: "./protoc-gen-connect-ktor"
    main: "./cmd/protoc-gen-connect-ktor"
    binary: protoc-gen-connect-ktor
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: protoc-gen-connect-ktor
    formats: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

gomod:
  dir: ./protoc-gen-connect-ktor

report_sizes: true

release:
  draft: true

brews:
  - name: protoc-gen-connect-ktor
    ids:
      - protoc-gen-connect-ktor
    repository:
      owner: ichizero
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    commit_author:
      name: github-actions[bot]
      email: 41898282+github-actions[bot]@users.noreply.github.com
    description: "Protoc plugin to generate Ktor server code"
    homepage: "https://github.com/ichizero/connect-ktor"
