# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - dir: "protoc-gen-connect-ktor"
    main: "./cmd/protoc-gen-connect-ktor"
    binary: "protoc-gen-connect-ktor"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}}
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
  mod: mod
  dir: ./protoc-gen-connect-ktor

report_sizes: true

brews:
  - repository:
      owner: ichizero
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
