version: "3"
tasks:
  generate:
    aliases:
      - generate
    deps:
      - build-protoc-plugin
    cmds:
      - buf generate --template ktor-serialization-connect/src/test/resources/buf.gen.yaml -o ktor-serialization-connect buf.build/connectrpc/eliza
      - buf generate --template protoc-gen-connect-ktor/src/test/resources/buf.gen.yaml -o protoc-gen-connect-ktor buf.build/connectrpc/eliza
  lint:
    cmds:
      - ./gradlew spotlessKotlinCheck
  build-protoc-plugin:
    aliases:
      - build-pp
    cmds:
      - ./gradlew :protoc-gen-connect-ktor:shadowJarExecutable -x test
  test:
    deps:
      - generate
    cmds:
      - ./gradlew test
  build:
    deps:
      - generate
    cmds:
      - ./gradlew build
  diff-check:
    deps:
      - generate
    cmds:
      - git diff --exit-code --ignore-matching-lines="//"
