version: "3"
includes:
  plugin:
    taskfile: ./protoc-gen-connect-ktor/Taskfile.yaml
    dir: ./protoc-gen-connect-ktor
tasks:
  generate:
    aliases:
      - gen
    deps:
      - plugin:build
    cmds:
      - for: ["library", "protoc-gen-connect-ktor-test"]
        task: generate-for-test
        vars:
          DIR: "{{ .ITEM }}"
  generate-for-test:
    internal: true
    dir: "{{ .DIR }}"
    cmds:
      - buf generate --template src/test/resources/buf.gen.yaml buf.build/connectrpc/eliza
  lint:
    cmds:
      - ./gradlew spotlessKotlinCheck
  test:
    deps:
      - generate
    cmds:
      - ./gradlew test
  build:
    deps:
      - generate
    cmds:
      - ./gradlew build
  diff-check:
    deps:
      - generate
    cmds:
      - git diff --exit-code --ignore-matching-lines="//"
