# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
includes:
  library:
    taskfile: ./library/Taskfile.yaml
    dir: ./library
  plugin:
    taskfile: ./protoc-gen-connect-ktor/Taskfile.yaml
    dir: ./protoc-gen-connect-ktor
  plugin-test:
    taskfile: ./protoc-gen-connect-ktor-test/Taskfile.yaml
    dir: ./protoc-gen-connect-ktor-test
tasks:
  lint:
    cmds:
      - ./gradlew spotlessKotlinCheck
      - task: plugin:lint
  build:
    cmds:
      - task: plugin:build
  generate:
    aliases:
      - gen
    deps:
      - build
    cmds:
      - task: library:generate
      - task: plugin-test:generate
  test:
    deps:
      - generate
    cmds:
      - ./gradlew test
      - task: plugin:test
  release-snapshot:
    cmds:
      - goreleaser release --snapshot --clean
