version: "3"
tasks:
  generate:
    aliases:
      - gen
    deps:
      - build-protoc-plugin
    cmds:
      - cd library && buf generate
      - cd protoc-gen-connect-ktor && buf generate
  lint:
    cmds:
      - ./gradlew spotlessKotlinCheck
  build-protoc-plugin:
    aliases:
      - build-pp
    cmds:
      - ./gradlew :protoc-gen-connect-ktor:shadowJarExecutable -x test
  test:
    deps:
      - generate
    cmds:
      - ./gradlew test
  build:
    deps:
      - generate
    cmds:
      - ./gradlew build
  diff-check:
    deps:
      - generate
    cmds:
      - git diff --exit-code --ignore-matching-lines="//"
