features:
  versions:
    - HTTP_VERSION_1
  protocols:
    - PROTOCOL_CONNECT
  codecs:
    - CODEC_PROTO
    - CODEC_JSON
  compressions:
    - COMPRESSION_IDENTITY
  stream_types:
    - STREAM_TYPE_UNARY
    - STREAM_TYPE_CLIENT_STREAM
  supports_h2c: false
  # CIO does not implement HTTPS upstream
  # (UnsupportedOperationException: CIO Engine does not currently support HTTPS).
  supports_tls: false
  supports_tls_client_certs: false
  supports_trailers: true
  supports_half_duplex_bidi_over_http1: false
  supports_connect_get: true
  supports_message_receive_limit: false
