# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  format:
    cmds:
      - go fmt ./...
  lint:
    cmds:
      - go vet ./...
  build:
    cmds:
      - go build -ldflags="-s -w" -trimpath -o="./out/protoc-gen-connect-ktor" ./cmd/protoc-gen-connect-ktor
  test:
    cmds:
      - go test -v ./...
