package generator

import (
	"sync"
	"text/template"

	"github.com/ichizero/connect-ktor/protoc-gen-connect-ktor/internal/tmplfunc"
)

var loadTemplate = sync.OnceValues(func() (*template.Template, error) {
	return template.New("service_handler").Funcs(tmplfunc.Map).Parse(kotlinServiceTemplate)
})

type serviceData struct {
	ProtoPackageName string
	JavaPackageName  string
	SourceFileName   string
	Name             string
	Comment          string
	Methods          []*methodData
	// HasClientStream is true when any of Methods has StreamType == streamTypeClient.
	// Drives conditional imports for Flow / handleClientStream.
	HasClientStream bool
	// HasIdempotent is true when any unary method is idempotent (NO_SIDE_EFFECTS).
	// Drives conditional imports for handleGet / io.ktor.server.resources.get.
	HasIdempotent bool
}

type methodData struct {
	Name           string
	Comment        string
	InputTypeName  string
	OutputTypeName string
	StreamType     streamType
	Idempotent     bool
}

const kotlinServiceTemplate = `// Code generated by connect-ktor. DO NOT EDIT.
//
// Source: {{ .SourceFileName }}
//
package {{ .JavaPackageName }}

import com.connectrpc.ResponseMessage
import io.github.ichizero.connect.ktor.handle
{{- if .HasClientStream }}
import io.github.ichizero.connect.ktor.streaming.handleClientStream
{{- end }}
{{- if .HasIdempotent }}
import io.github.ichizero.connect.ktor.handleGet
{{- end }}
import io.ktor.resources.Resource
import io.ktor.server.application.ApplicationCall
{{- if .HasIdempotent }}
import io.ktor.server.resources.get
{{- end }}
import io.ktor.server.resources.post
import io.ktor.server.routing.Route
{{- if .HasClientStream }}
import kotlinx.coroutines.flow.Flow
{{- end }}

{{ .Comment -}}
interface {{ .Name }}HandlerInterface {
    {{- range .Methods }}
    {{- .Comment | nIndent 4 -}}
    {{- if eq (printf "%s" .StreamType) "Unary" }}
    suspend fun {{ .Name | toLowerFirst }}(request: {{ .InputTypeName }}, call: ApplicationCall): ResponseMessage<{{ .OutputTypeName }}>
    {{- else if eq (printf "%s" .StreamType) "Client" }}
    suspend fun {{ .Name | toLowerFirst }}(requests: Flow<{{ .InputTypeName }}>, call: ApplicationCall): ResponseMessage<{{ .OutputTypeName }}>
    {{- end }}
    {{- end }}

    object Procedures {
        {{- range .Methods }}
        @Resource("/{{ $.ProtoPackageName }}.{{ $.Name }}/{{ .Name }}")
        class {{ .Name }}
        {{- end }}
    }
}

fun Route.{{ .Name | toLowerFirst }}(handler: {{ .Name }}HandlerInterface) {
    {{- range .Methods }}
    {{- if eq (printf "%s" .StreamType) "Unary" }}
    post<{{ $.Name }}HandlerInterface.Procedures.{{ .Name }}, {{ .InputTypeName }}>(handle(handler::{{ .Name | toLowerFirst }}))
    {{- if .Idempotent }}
    get<{{ $.Name }}HandlerInterface.Procedures.{{ .Name }}>(handleGet<{{ $.Name }}HandlerInterface.Procedures.{{ .Name }}, {{ .InputTypeName }}, {{ .OutputTypeName }}>(handler::{{ .Name | toLowerFirst }}))
    {{- end }}
    {{- else if eq (printf "%s" .StreamType) "Client" }}
    post<{{ $.Name }}HandlerInterface.Procedures.{{ .Name }}>(handleClientStream(handler::{{ .Name | toLowerFirst }}))
    {{- end }}
    {{- end }}
}
`
